# Generated by Django 3.1.1 on 2021-03-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restcomplaints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='passsword',
            new_name='password',
        ),
    ]
