# Generated by Django 3.1.1 on 2021-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restcomplaints', '0003_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='occurrence',
            field=models.IntegerField(),
        ),
    ]
