# Generated by Django 3.1.1 on 2021-03-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restcomplaints', '0004_auto_20210314_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.CharField(default='pending resolution', max_length=100),
        ),
    ]
