# Generated by Django 3.1.1 on 2021-03-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restcomplaints', '0008_auto_20210316_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_admin',
            new_name='admin',
        ),
    ]
